# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html

# Site
title: Jean-Marc Fontaine
author: Jean-Marc Fontaine
language: fr
timezone: Europe/Paris

# URL
url: http://www.jmfontaine.net/
root: /

# Writing
future: no
new_post_name: :year-:month-:day-:title.md

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape

feed:
  type: rss2
  path: rss2.xml
  limit: 10
  content: true

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
